name: Build and Push OpenNMS


on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug

env:
  IMAGE_NAME: medsalahmejri/opennms

jobs:
  build:
    name: Build and Push Docker Image
    runs-on: self-hosted  # Utilisation du runner auto-hébergé

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Vérifier si Docker est installé
        run: docker --version

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: |
          docker build -t $IMAGE_NAME:${{ github.sha }} .
          docker tag $IMAGE_NAME:${{ github.sha }} $IMAGE_NAME:latest

      - name: Push Docker image
        run: |
          docker push $IMAGE_NAME:${{ github.sha }}
          docker push $IMAGE_NAME:latest
